//
//  KBVolumeAnimation.h
//  KBVolumeAnimation
//
//  Created by Kane Buckthorpe on 09/04/2019.
//  Copyright © 2019 Kane. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>



typedef NS_ENUM(NSInteger, KBVolumeAnimationResizingBehavior)
{
    KBVolumeAnimationResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    KBVolumeAnimationResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    KBVolumeAnimationResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    KBVolumeAnimationResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

};

extern CGRect KBVolumeAnimationResizingBehaviorApply(KBVolumeAnimationResizingBehavior behavior, CGRect rect, CGRect target);


@interface KBVolumeAnimation : NSObject

// Drawing Methods
+ (void)drawVolumeSliderWithValue: (CGFloat)value color:(UIColor*)color;
+ (void)drawVolumeSliderWithFrame: (CGRect)targetFrame resizing: (KBVolumeAnimationResizingBehavior)resizing value: (CGFloat)value color:(UIColor*)color;

// Generated Images
+ (UIImage*)imageOfVolumeSliderWithValue: (CGFloat)value color:(UIColor*)color;

@end
